FirstDemo:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: hu89384.me-central2.gcp
      user: manaspradhan2004
      password: t9sD7sJ4GtjBzHZ
      role: accountadmin
      database: RAW
      warehouse: transforming
      schema: JAFFLE_SHOP
      threads: 1
      client_session_keep_alive: False